language: generic
sudo: false
env:
  matrix:
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask

script:
  - emacs --version
  - emacs --batch --funcall batch-byte-compile number-to-word.el
  - emacs --batch -L . --load ert --load number-to-word-tests --funcall ert-run-tests-batch-and-exit
